# host = "localhost"
# user = "postgres"
# postgresport = 5001
# database_airquality = "testing"
# password_airquality = "9664241907"
# database_parking = "testing"
# password_parking = "9664241907"
# mongoport = 27017
# database_events = "testing"
# password_events = "9664241907"
host = "postgres"
user = "admin"
postgresport = 5432
database_airquality = "postgres"
password_airquality = "secret"
database_parking = "postgres"
password_parking = "secret"
mongoport = 27017
database_events = "postgres"
password_events = "secret"